import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Download, 
  AlertTriangle, 
  CheckCircle, 
  Clock, 
  Stethoscope,
  TrendingUp,
  Shield,
  Heart,
  Brain
} from "lucide-react";

interface WoundAssessmentResultsProps {
  imageUrl: string;
  analysisData: {
    wound_characteristics?: string;
    healing_stage?: string;
    infection_signs?: string;
    care_recommendations?: string;
    confidence_score?: number;
    [key: string]: any; // Allow for additional properties
  };
}

export const WoundAssessmentResults = ({ imageUrl, analysisData }: WoundAssessmentResultsProps) => {
  // Comprehensive debug logging
  console.log('🔍 WoundAssessmentResults DEBUG INFO:');
  console.log('📸 imageUrl:', imageUrl);
  console.log('📊 analysisData:', analysisData);
  console.log('🔢 imageUrl type:', typeof imageUrl);
  console.log('🔢 analysisData type:', typeof analysisData);
  console.log('✅ imageUrl exists:', !!imageUrl);
  console.log('✅ analysisData exists:', !!analysisData);
  
  if (analysisData) {
    console.log('🧠 analysisData keys:', Object.keys(analysisData));
    console.log('🎯 confidence_score:', analysisData.confidence_score);
    console.log('🩹 wound_characteristics:', analysisData.wound_characteristics?.substring(0, 100) + '...');
  }

  // Safety checks to prevent blank page
  if (!imageUrl || !analysisData) {
    console.error('❌ MISSING REQUIRED PROPS:', { 
      imageUrl: !!imageUrl, 
      analysisData: !!analysisData,
      imageUrlValue: imageUrl,
      analysisDataValue: analysisData 
    });
    
    return (
      <div className="space-y-6">
        <Card className="border-red-200 bg-red-50">
          <CardContent className="pt-6">
            <div className="flex gap-3">
              <AlertTriangle className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className="font-medium text-red-800 mb-1">Error Loading Results</p>
                <p className="text-red-700">
                  There was an issue loading your assessment results. Please try again.
                </p>
                <div className="mt-2 text-xs text-red-600">
                  <p>Debug Info:</p>
                  <p>• Image URL: {imageUrl ? '✅ Present' : '❌ Missing'}</p>
                  <p>• Analysis Data: {analysisData ? '✅ Present' : '❌ Missing'}</p>
                  {analysisData && <p>• Data Keys: {Object.keys(analysisData).join(', ')}</p>}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  const handleDownloadReport = () => {
    try {
      const reportContent = `
WOUND ASSESSMENT REPORT - AI ANALYSIS
Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
Analysis Method: GPT-4.1 Vision AI

WOUND CHARACTERISTICS:
${analysisData.wound_characteristics || 'Not available'}

HEALING STAGE:
${analysisData.healing_stage || 'Not available'}

INFECTION ASSESSMENT:
${analysisData.infection_signs || 'Not available'}

CARE RECOMMENDATIONS:
${analysisData.care_recommendations || 'Not available'}

AI CONFIDENCE SCORE: ${analysisData.confidence_score ? (analysisData.confidence_score * 100).toFixed(1) + '%' : 'Not available'}

---
IMPORTANT MEDICAL DISCLAIMER:
This AI assessment uses GPT-4.1 vision technology for informational purposes only and should not replace professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for proper wound care and if you notice signs of infection, worsening condition, or have any concerns about your wound.

Generated by Avra Health AI Wound Assessment Platform
      `;

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ai-wound-assessment-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      console.log('📥 Report downloaded successfully');
    } catch (error) {
      console.error('💥 Error downloading report:', error);
    }
  };

  const getConfidenceColor = (score?: number) => {
    if (!score) return "bg-gray-500";
    if (score >= 0.9) return "bg-green-600";
    if (score >= 0.8) return "bg-green-500";
    if (score >= 0.7) return "bg-yellow-500";
    return "bg-red-500";
  };

  const getConfidenceText = (score?: number) => {
    if (!score) return "Unknown";
    if (score >= 0.9) return "Very High Confidence";
    if (score >= 0.8) return "High Confidence";
    if (score >= 0.7) return "Good Confidence";
    return "Low Confidence";
  };

  const formatAnalysisText = (text?: string) => {
    if (!text) return "Analysis not available";
    // Split long paragraphs into more readable sections
    return text.split('. ').map((sentence, index, array) => {
      if (index === array.length - 1) return sentence;
      return sentence + '.';
    }).join(' ');
  };

  console.log('✅ Rendering WoundAssessmentResults successfully');

  return (
    <div className="space-y-6">
      {/* Debug Info Card */}
      <Card className="bg-blue-50 border-blue-200">
        <CardContent className="pt-6">
          <div className="flex gap-3">
            <Brain className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-blue-800 mb-1">🔍 Debug Information</p>
              <div className="text-blue-700 text-xs space-y-1">
                <p>• Image URL: {imageUrl ? '✅ Present' : '❌ Missing'}</p>
                <p>• Analysis Data: {analysisData ? '✅ Present' : '❌ Missing'}</p>
                <p>• Confidence Score: {analysisData.confidence_score || 'N/A'}</p>
                <p>• Data Keys: {Object.keys(analysisData).join(', ')}</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Header */}
      <div className="text-center">
        <h2 className="text-2xl font-bold text-foreground mb-2 flex items-center justify-center gap-2">
          <Brain className="h-6 w-6 text-blue-600" />
          AI Wound Assessment Results
        </h2>
        <p className="text-muted-foreground">
          Analysis completed using GPT-4.1 Vision AI on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
        </p>
      </div>

      {/* Confidence Score */}
      {analysisData.confidence_score && (
        <Card className="border-l-4 border-l-blue-600">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <TrendingUp className="h-5 w-5 text-blue-600" />
                </div>
                <div>
                  <p className="font-medium">AI Analysis Confidence</p>
                  <p className="text-sm text-muted-foreground">GPT-4.1 vision assessment reliability</p>
                </div>
              </div>
              <Badge className={`${getConfidenceColor(analysisData.confidence_score)} text-white`}>
                {getConfidenceText(analysisData.confidence_score)} ({(analysisData.confidence_score * 100).toFixed(1)}%)
              </Badge>
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Analyzed Image */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-blue-600" />
              Analyzed Image
            </CardTitle>
            <CardDescription>Your uploaded wound photo processed by AI</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="aspect-square w-full overflow-hidden rounded-lg border">
              <img
                src={imageUrl}
                alt="AI analyzed wound"
                className="w-full h-full object-cover"
                onLoad={() => console.log('✅ Image loaded successfully')}
                onError={(e) => {
                  console.error('❌ Image failed to load:', imageUrl);
                  e.currentTarget.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjZjNmNGY2Ii8+PHRleHQgeD0iNTAlIiB5PSI1MCUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZmlsbD0iIzk5YTNhZiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iPkltYWdlIE5vdCBBdmFpbGFibGU8L3RleHQ+PC9zdmc+';
                }}
              />
            </div>
          </CardContent>
        </Card>

        {/* Assessment Summary */}
        <div className="space-y-4">
          {/* Wound Characteristics */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <Stethoscope className="h-5 w-5 text-blue-600" />
                Wound Characteristics
              </CardTitle>
              <CardDescription>AI visual analysis of wound features</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed">{formatAnalysisText(analysisData.wound_characteristics)}</p>
            </CardContent>
          </Card>

          {/* Healing Stage */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <Clock className="h-5 w-5 text-green-600" />
                Healing Stage Assessment
              </CardTitle>
              <CardDescription>AI evaluation of healing progression</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed">{formatAnalysisText(analysisData.healing_stage)}</p>
            </CardContent>
          </Card>

          {/* Infection Signs */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <AlertTriangle className="h-5 w-5 text-red-500" />
                Infection Risk Assessment
              </CardTitle>
              <CardDescription>AI analysis of infection indicators</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed">{formatAnalysisText(analysisData.infection_signs)}</p>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Care Recommendations */}
      <Card className="border-l-4 border-l-green-600">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Heart className="h-5 w-5 text-green-600" />
            AI Care Recommendations
          </CardTitle>
          <CardDescription>Personalized guidance based on AI visual analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="prose prose-sm max-w-none">
            <p className="leading-relaxed">{formatAnalysisText(analysisData.care_recommendations)}</p>
          </div>
        </CardContent>
      </Card>

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4">
        <Button onClick={handleDownloadReport} className="flex-1 bg-blue-600 hover:bg-blue-700">
          <Download className="h-4 w-4 mr-2" />
          Download AI Assessment Report
        </Button>
        <Button variant="outline" className="flex-1">
          <CheckCircle className="h-4 w-4 mr-2" />
          Schedule Professional Consultation
        </Button>
      </div>

      {/* Medical Disclaimer */}
      <Card className="bg-yellow-50 border-yellow-200">
        <CardContent className="pt-6">
          <div className="flex gap-3">
            <AlertTriangle className="h-5 w-5 text-yellow-600 flex-shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-yellow-800 mb-1">Important Medical Disclaimer</p>
              <p className="text-yellow-700 leading-relaxed">
                This AI assessment uses GPT-4.1 vision technology for informational purposes only and should not replace professional medical advice, 
                diagnosis, or treatment. While our AI provides detailed analysis based on visual assessment, always consult with a qualified healthcare provider 
                for proper wound care and if you notice signs of infection, worsening condition, or have any concerns about your wound.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

